### ISSUE TITLE
test时出错

### ISSUE THREAD

**Issue by yutao98** [RuiqiWang00/Sparseinst-ms#1]
@RuiqiWang00 您好，我在用网盘里的模型测试单张图片时报错：
> Traceback (most recent call last):`
  File "C:\Users\60271\Desktop\mindspore\test.py", line 208, in <module>
    main()
  File "C:\Users\60271\Desktop\mindspore\test.py", line 199, in main
    _ = [visualization(res['pred_masks'], res['ori_image'], res['image_id'], './') for res in results]
  File "C:\Users\60271\Desktop\mindspore\test.py", line 199, in <listcomp>
    _ = [visualization(res['pred_masks'], res['ori_image'], res['image_id'], './') for res in results]
KeyError: 'pred_masks'
>
这是我使用的命令：
`python test.py --checkpoint configs/sparse_inst_r50_giam_ceaffc.ckpt  --image_name configs/1.jpg --visualize`
我需要做别的操作吗？
此外，能否请您更新一个训练过程的tutorial？感激不尽

**Comment by RuiqiWang00** [comment]
这说明没有检测到物体
暂时没有提供训练的实现，现在使用的权重是用pytorch训的权重转换过去的

**Comment by Krist1798** [comment]
好的，感谢回复，我测试了几张图片并且修改了MASK_THRESHOLD之后依然是同样的错误，

**Comment by yutao98** [comment]
好的，感谢回复，不过我测试了几张图片并修改了MASK_THRESHOLD之后仍然是同样的错误，可能因为使用的是cpu版本的mindspore吧 :(
